### ISSUE TITLE
gpPred method has started failing

### ISSUE THREAD

**Issue by cboettig** [cboettig/gpmanagement#1]
@danielturek I'm getting this same error locally and on `travis`, looks like your `pgPred()` function is now failing on me with an "undefined class" error (when running your basic example).  Perhaps something changed on the devel branch recently since this was working yesterday I believe? (though before I had travis turned on so I can't link those logs.)

Here's the [error and trace on travis](https://travis-ci.org/cboettig/gpmanagement/builds/67577443#L2884).  Any ideas?

(p.s. I know you're away, just pinning you now so I don't forget).

**Comment by danielturek** [comment]
Hmm..  I believe this has to do with the dynamically generated classes, and where they are defined and available / not available.  I looked at it a bit yesterday, and will continue to do so.  Thanks for flagging this.

**Comment by cboettig** [comment]
Looks like this issue is solved by @danielturek 's PR in #2, though this introduces some issues of package structure which we might want to revisit later.
