### ISSUE TITLE
Appropriate non-dimensionalization / scaling for data

### ISSUE THREAD

**Issue by cboettig** [cboettig/gpmanagement#4]
We should decide on how we handle scaling the any data so that results are comparable.  For instance, here are the estimates from two otherwise identical simulations, scaled to carrying capacity of 10 vs 100, showing significantly different length scales:

![](https://github.com/cboettig/gpmanagement/blob/master/inst/notes/non-dimensionalization_files/figure-markdown_github/unnamed-chunk-7-1.png)

![](https://github.com/cboettig/gpmanagement/raw/master/inst/notes/non-dimensionalization_files/figure-markdown_github/unnamed-chunk-11-1.png)

This doesn't appear to be due to carry over influence of the prior on the length-scale -- indeed I attempt to bias the prior intentionally to the opposite direction (smaller length scale in the first, longer in the second), but this appears to have very little effect.  The length scale is a bit longer in absolute terms in the second case (~20 instead of ~10), but relative to the data that's much shorter, giving the GP mean prior of 0 a much stronger effect.  

Reproducible example here. https://github.com/cboettig/gpmanagement/blob/6781f3414bdce15e1a608a48705eb080ef80d825/inst/notes/non-dimensionalization.md

@danielturek thoughts?

**Comment by cboettig** [comment]
Basically, we want results where the length-scale isn't much longer than the region over where we have data, such that we get results more like https://github.com/cboettig/gpmanagement/blob/6781f3414bdce15e1a608a48705eb080ef80d825/inst/notes/non-dimensionalization_files/figure-markdown_github/unnamed-chunk-11-1.png with larger uncertainty outside of the data, rather than like https://github.com/cboettig/gpmanagement/blob/6781f3414bdce15e1a608a48705eb080ef80d825/inst/notes/non-dimensionalization_files/figure-markdown_github/unnamed-chunk-7-1.png  .  I just haven't quite wrapped my head around this problem -- why should the length scale be proportionally longer when all we've done is change units?  What do we do about it? 


This issue will bear on things in two ways:

- As it makes most sense to work in log space (growth noise should be multiplicative, where as the GP models the process noise as additive, so taking logs solves this), roughly speaking most of the data will be 'small' and thus more susceptible to this issue.  

- The real world data naturally has very different scales to it depending on the species (though it may not look so different after we take logs) I suspect the appropriate thing to do is define some scale transformation, so that after transformation all of the data is scaled appropriately (e.g. on 0, 1 or something) -- since the fit should obviously be independent of the units / scale of the given data series.  

- Steve puts forward one approach to rescaling in his [original GP paper](http://doi.org/10.1139/cjfas-2012-0315) which I had previously overlooked; that might be a good place to start, though if I follow this scales the priors to the data rather than just transforming the data.  Maybe take a look at what he's got there under priors specification after eqn 7 and see what you think.

**Comment by danielturek** [comment]
Certainly not closing this issue but see PR #5 for progress and updates towards this.

**Comment by danielturek** [comment]
Yes, as you said, the results make a lot more sense now.  Let me know when you remake the note on the scalaing issue:
https://github.com/cboettig/gpmanagement/blob/master/inst/notes/non-dimensionalization.md

And you're not off the hook for showing me how you easily do that, at some point.

I'm thinking about sensible and robust ways for assigning a prior for `rho` -- which I think we both agree is important.

**Comment by danielturek** [comment]
@cboettig, is the link you provided in your earlier comment above:

Steve puts forward one approach to rescaling in his [original GP paper](http://www.nrcresearchpress.com/doi/abs/10.1139/cjfas-2012-0315#.Vd-FLrxViko) which I had previously overlooked;

the one you intended?  Thx.

**Comment by cboettig** [comment]
nope, good catch.  Try this one: http://doi.org/10.1139/f05-073

not sure how I got my DOIs crossed there.

**Comment by danielturek** [comment]
@cboettig , I did some looking at the priors.  I added a note describing my work to `gpmanagement`, but the LaTeX in there didn't render right... is there a trick to getting LaTeX equations to render in rmarkdown?

It works fine when rendering to html.

[My work on the dimensional scaling can be found here](http://danielturek.github.io/public/dimensional-scaling/dimensional-scaling.html)

**Comment by cboettig** [comment]
no bananas; github blocks arbitrary javascript so it won't reader MathJax LaTeX.  That's one reason why I often stick things in my notebook instead of just in the github repo (e.g. just to have it rendered as HTML).  

Write-up looks pretty good.  So, to the question-at-hand: looks like we're not going to escape the prior having influence, that's just the nature of the problem.  I like the uniform priors, I have no idea what the point of the improper priors with infinite variance was but it seems good to avoid.  

Your construction looks reasonable to me; certainly the posteriors plots give the appearance of being quite different from the priors.  And it gives us a way to scale the prior to each data set in a sensible way so that the natural scale of the data isn't influencing the outcome.  Perhaps we need a similar scaling for the other priors?

Is it just the length-scale that is strongly influenced by the prior, or the variance terms as well? 

I think we can defend informative priors so long as we are transparent about the issue.  In some sense this is doing exactly what we need from a model -- we take away the need to make arbitrarily strong assumptions about parameterization, and replace that with toggles that can be better informed by the biology. Whereas the parametric model makes a strong assumption of how points are correlated all possible values of state space -- a range beyond that of the data, we make a weaker assumption (e.g. a prior that could at least in principle differ given substantial data) that points are correlated at least over the range of observed data.

**Comment by danielturek** [comment]
Thanks for explaining about github and LaTeX.  Unfortunate.

I like the uniform priors, as well.  I try to use them in many situations, since (at least for a given parametrization) they seem the most transparent to me.

I think we're good as far as the other paramters -- just the other two standard deviation terms, `sigmaOE` and `sigmaGP`.  In the respective prior/posterior plots, with huge uniform priors on them, the posteriors are well-behaved over a compact region.  We could imagine pathalogical cases where the data is so extremely varied that the bound of 1e5 isn't big enough, but I suspect it's fine for ecological applications.

Your reasoning about the use of (slightly) informative priors makes good sense to me.

**Comment by danielturek** [comment]
I pushed changes to the `gp_setup` function in `R / gp.R`, to use the dynamic (data-dependent) prior for `rho` if no other priors are specified.  Tested on a few examples, and it appears to work.

Does that close this issue?

**Comment by cboettig** [comment]
Yup, I tested on my Rmd's too and looks good, so let's close
